"""
Task 22 Step 2 -- OOS evaluation using the FROZEN Task 21 spec.

Applies the frozen early-failure model family (docs/research/
task21_frozen_early_failure_spec.json) to genuinely out-of-sample trades
generated by the frozen 0.20% strategy over 2026-08-17 onward. No
refitting, no recalibration, no threshold changes -- this script only
APPLIES what was already frozen.

Also runs focused leakage and determinism tests (Sections 13-14), and
enforces the pre-registered 40-trade minimum before any statistical
interpretation (Section 6/15).
"""
import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path("c:/workspace/TalonX")
sys.path.insert(0, str(REPO))

from talonx_quant.session import get_session  # noqa: E402
from zoneinfo import ZoneInfo  # noqa: E402
import datetime as _dt  # noqa: E402

_ET = ZoneInfo("America/New_York")

OUT = REPO / "results" / "task22_oos_early_failure"
OUT.mkdir(parents=True, exist_ok=True)

OOS_DATA_DIR = REPO / "data" / "historical_1m" / "task22_oos"
DISCOVERY_DATA_DIR = REPO / "data" / "historical_1m" / "task7b_alpaca_long_history"
REPLAY_TRADES = OUT / "replay" / "task22_oos_trades.csv"
FROZEN_SPEC_PATH = REPO / "docs" / "research" / "task21_frozen_early_failure_spec.json"

MIN_OOS_TRADES = 40
MODEL_FEATURES = ["current_R", "running_MAE_R", "consecutive_adverse_bars"]
HORIZONS = [1, 2, 3, 5]

_raw_cache: dict[str, pd.DataFrame] = {}


def raw_bars(symbol: str) -> pd.DataFrame:
    if symbol not in _raw_cache:
        df = pd.read_csv(OOS_DATA_DIR / f"{symbol}.csv", parse_dates=["timestamp"])
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
        _raw_cache[symbol] = df.set_index("timestamp").sort_index()
    return _raw_cache[symbol]


# ------------------------------------------------------------------
# Feature extraction -- IDENTICAL logic to research/scripts/
# task21_early_failure_audit.py's build_r_series / horizon_features,
# reproduced here (not imported, since that module's __main__ runs on
# import) to guarantee bit-identical behavior on OOS data. Any drift
# between the two copies would itself be a bug worth catching -- see
# the determinism test below, which checks this copy's internal
# consistency, and Section 13's leakage test, which checks the horizon
# cutoff itself.
# ------------------------------------------------------------------

def build_r_series(row) -> pd.DataFrame | None:
    bars = raw_bars(row.symbol)
    window = bars.loc[row.entry_timestamp:row.exit_timestamp]
    if window.empty:
        return None
    entry = row.entry_price
    risk = row.risk_dollars_per_share
    if row.direction == "bullish":
        high_R = (window["high"] - entry) / risk
        low_R = (window["low"] - entry) / risk
        close_R = (window["close"] - entry) / risk
    else:
        high_R = (entry - window["low"]) / risk
        low_R = (entry - window["high"]) / risk
        close_R = (entry - window["close"]) / risk
    out = pd.DataFrame({"high_R": high_R, "low_R": low_R, "close_R": close_R, "volume": window["volume"]})
    out["minutes"] = (out.index - row.entry_timestamp).total_seconds() / 60.0
    return out


def horizon_model_features(series: pd.DataFrame, T: int) -> dict | None:
    win = series[series.minutes <= T]
    if win.empty:
        return None
    last_close_R = float(win.close_R.iloc[-1])
    running_mae = float(win.low_R.cummin().iloc[-1])
    closes = pd.concat([pd.Series([0.0]), win.close_R.reset_index(drop=True)])
    bar_returns = closes.diff().dropna().to_numpy()

    def max_streak(mask: np.ndarray) -> int:
        best = cur = 0
        for m in mask:
            cur = cur + 1 if m else 0
            best = max(best, cur)
        return best
    consecutive_adverse = max_streak(bar_returns < 0)
    return dict(current_R=last_close_R, running_MAE_R=running_mae, consecutive_adverse_bars=consecutive_adverse,
                n_bars_used=int(len(win)), max_minute_used=float(win.minutes.max()))


def apply_frozen_model(features: dict, horizon_spec: dict) -> dict:
    mu = np.array(horizon_spec["standardization_mean"])
    sd = np.array(horizon_spec["standardization_std"])
    coef = np.array(horizon_spec["coefficients"])
    intercept = horizon_spec["intercept"]
    x = np.array([features[c] for c in MODEL_FEATURES])
    xz = (x - mu) / sd
    logit = intercept + np.dot(coef, xz)
    prob_immediate_failure = 1.0 / (1.0 + np.exp(-logit))
    predicted_class = "IMMEDIATE_FAILURE" if prob_immediate_failure >= 0.5 else "NOT_IMMEDIATE_FAILURE"
    return dict(prob_immediate_failure=float(prob_immediate_failure), predicted_class=predicted_class)


def classify_path_task20_style(row, walk_high_R, walk_low_R, gross_R) -> str:
    """Mirrors research/scripts/task20_excursion_audit.py's classify_path
    + finalize_class logic exactly, applied to a completed OOS trade."""
    max_mfe = float(walk_high_R.cummax().iloc[-1])
    is_stop = row.exit_reason == "STOP"
    is_winner_exit = row.exit_reason in ("TARGET", "END_OF_SESSION")
    final_positive = gross_R > 0
    if is_stop:
        if max_mfe < 0.25:
            return "IMMEDIATE_FAILURE"
        if max_mfe < 1.0:
            return "SMALL_FAVORABLE_THEN_STOP"
        return "LARGE_FAVORABLE_THEN_REVERSAL"
    if is_winner_exit and final_positive:
        hit_05 = walk_high_R.cummax() >= 0.50
        if hit_05.any():
            pos = walk_high_R.index.get_loc(hit_05.idxmax())
            post_min = float(walk_low_R.iloc[pos:].min())
            if post_min <= 0:
                return "DEEP_RETRACE_WINNER"
        return "MONOTONIC_WINNER"
    return "OTHER"


def session_bucket_of(entry_ts) -> str:
    sess = get_session(entry_ts)
    if sess == "pre_market":
        return "PREMARKET"
    if sess == "regular":
        return "REGULAR"
    et_time = entry_ts.astimezone(_ET).time()
    if et_time == _dt.time(16, 0):
        return "CLOSING_AUCTION_BOUNDARY_16:00ET"
    return "POST_MARKET_CLOSED"


def sha256_obj(obj) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, default=str).encode()).hexdigest()[:16]


if __name__ == "__main__":
    print("=== Section 2: frozen spec integrity ===")
    spec = json.loads(FROZEN_SPEC_PATH.read_text())
    recomputed_hash_input = {k: v for k, v in spec.items() if k != "frozen_spec_hash"}
    recomputed = hashlib.sha256(json.dumps(recomputed_hash_input, indent=2, sort_keys=False).encode()).hexdigest()[:16]
    print(f"stored frozen_spec_hash={spec['frozen_spec_hash']}, recomputed={recomputed}, "
          f"match={recomputed == spec['frozen_spec_hash']}")

    from talonx_backtest.reproducibility import get_dataset_hash, get_git_commit
    oos_hash = get_dataset_hash(str(OOS_DATA_DIR))
    integrity = dict(
        frozen_spec_hash=spec["frozen_spec_hash"], frozen_spec_hash_recomputed_matches=(recomputed == spec["frozen_spec_hash"]),
        oos_dataset_hash=oos_hash, discovery_dataset_hash_frozen=spec["discovery_dataset_hash"],
        discovery_dataset_hash_reconfirmed=get_dataset_hash(str(DISCOVERY_DATA_DIR)),
        git_commit=get_git_commit(),
    )
    print(json.dumps(integrity, indent=2))

    # ------------------------------------------------------------------
    # Section 5-6: load OOS trades (strategy-frozen replay output)
    # ------------------------------------------------------------------
    if not REPLAY_TRADES.exists():
        raise SystemExit(f"FAIL: OOS replay output not found at {REPLAY_TRADES} -- run the frozen-strategy replay first.")
    trades = pd.read_csv(REPLAY_TRADES, parse_dates=["signal_timestamp", "entry_timestamp", "exit_timestamp"])
    for c in ["signal_timestamp", "entry_timestamp", "exit_timestamp"]:
        trades[c] = pd.to_datetime(trades[c], utc=True)
    n_oos = len(trades)
    print(f"\n=== Section 3: OOS trade count = {n_oos} (minimum required = {MIN_OOS_TRADES}) ===")

    trades["risk_dollars_per_share"] = (trades.entry_price - trades.stop_price).abs()
    trades["session_bucket"] = trades.entry_timestamp.apply(session_bucket_of)
    trades.to_csv(OUT / "task22_oos_trades.csv", index=False)

    status = "OOS_ACCUMULATING" if n_oos < MIN_OOS_TRADES else "SUFFICIENT_SAMPLE"
    print(f"status: {status}")

    # ------------------------------------------------------------------
    # walk every OOS trade for path classification + build R-series once
    # ------------------------------------------------------------------
    series_map = {}
    path_classes = {}
    for _, row in trades.iterrows():
        s = build_r_series(row)
        if s is None:
            raise SystemExit(f"FAIL: no OOS bars found for {row.trade_id}")
        series_map[row.trade_id] = s
        path_classes[row.trade_id] = classify_path_task20_style(row, s.high_R, s.low_R, row.net_R)
    trades["path_class"] = trades.trade_id.map(path_classes)
    print("\nOOS path class counts:", trades.path_class.value_counts().to_dict())

    # ------------------------------------------------------------------
    # Section 7/13: frozen feature extraction per horizon + leakage test
    # ------------------------------------------------------------------
    print("\n=== Section 13: leakage tests ===")
    leakage_ok = True
    feature_rows = []
    prediction_rows = []
    for _, row in trades.iterrows():
        series = series_map[row.trade_id]
        for T in HORIZONS:
            feat = horizon_model_features(series, T)
            if feat is None:
                continue
            # LEAKAGE ASSERTION: every bar used must have elapsed minutes <= T
            if feat["max_minute_used"] > T + 1e-9:
                leakage_ok = False
                print(f"LEAKAGE DETECTED: {row.trade_id} horizon {T} used a bar at minute {feat['max_minute_used']}")
            feat_row = dict(trade_id=row.trade_id, horizon_min=T, **{k: v for k, v in feat.items()
                                                                       if k in MODEL_FEATURES})
            feat_row.update(n_bars_used=feat["n_bars_used"], max_minute_used=feat["max_minute_used"])
            feature_rows.append(feat_row)

            pred = apply_frozen_model(feat, spec["horizon_models"][str(T)])
            extra_feat = {k: v for k, v in feat_row.items() if k not in ("trade_id", "horizon_min")}
            prediction_rows.append(dict(
                trade_id=row.trade_id, horizon_min=T, symbol=row.symbol, entry_timestamp=str(row.entry_timestamp),
                session_bucket=row.session_bucket, path_class=row.path_class, exit_reason=row.exit_reason,
                gross_R=row.gross_R, net_R_5bps=row.net_R,
                prob_immediate_failure=pred["prob_immediate_failure"], predicted_class=pred["predicted_class"],
                **extra_feat,
            ))
    print(f"leakage_ok = {leakage_ok} ({len(feature_rows)} horizon-trade feature rows checked)")

    feat_df = pd.DataFrame(feature_rows)
    feat_df.to_csv(OUT / "task22_oos_features.csv", index=False)
    pred_df = pd.DataFrame(prediction_rows)
    pred_df.to_csv(OUT / "task22_oos_predictions.csv", index=False)
    print(f"wrote task22_oos_features.csv ({len(feat_df)} rows), task22_oos_predictions.csv ({len(pred_df)} rows)")

    # ------------------------------------------------------------------
    # Section 14: determinism test -- rerun feature extraction, compare hashes
    # ------------------------------------------------------------------
    print("\n=== Section 14: determinism test ===")
    feature_rows_2 = []
    for _, row in trades.iterrows():
        series = series_map[row.trade_id]
        for T in HORIZONS:
            feat = horizon_model_features(series, T)
            if feat is None:
                continue
            feature_rows_2.append(dict(trade_id=row.trade_id, horizon_min=T,
                                        **{k: v for k, v in feat.items() if k in MODEL_FEATURES}))
    hash_1 = sha256_obj(feature_rows)
    hash_2 = sha256_obj([{k: v for k, v in r.items() if k in ("trade_id", "horizon_min", *MODEL_FEATURES)}
                          for r in feature_rows_2])
    # compare on the shared key subset (feature_rows carries extra bookkeeping fields)
    hash_1_comparable = sha256_obj([{k: v for k, v in r.items() if k in ("trade_id", "horizon_min", *MODEL_FEATURES)}
                                     for r in feature_rows])
    determinism_ok = hash_1_comparable == hash_2
    print(f"run 1 hash={hash_1_comparable}, run 2 hash={hash_2}, determinism_ok={determinism_ok}")

    # ------------------------------------------------------------------
    # Section 8/9/10: metrics -- ONLY interpreted statistically if n>=40
    # ------------------------------------------------------------------
    metrics_rows = []
    econ_rows = []
    if n_oos >= MIN_OOS_TRADES:
        from sklearn.metrics import roc_auc_score
        for T in HORIZONS:
            pT = pred_df[pred_df.horizon_min == T]
            y_true = (pT.path_class == "IMMEDIATE_FAILURE").astype(int)
            y_pred_prob = pT.prob_immediate_failure
            y_pred_class = (pT.predicted_class == "IMMEDIATE_FAILURE").astype(int)
            if y_true.nunique() < 2:
                continue
            auc = roc_auc_score(y_true, y_pred_prob)
            tp = ((y_true == 1) & (y_pred_class == 1)).sum()
            fn = ((y_true == 1) & (y_pred_class == 0)).sum()
            tn = ((y_true == 0) & (y_pred_class == 0)).sum()
            fp = ((y_true == 0) & (y_pred_class == 1)).sum()
            sensitivity = tp / (tp + fn) if (tp + fn) else None
            specificity = tn / (tn + fp) if (tn + fp) else None
            precision = tp / (tp + fp) if (tp + fp) else None
            deep_winners = pT[pT.path_class == "DEEP_RETRACE_WINNER"]
            false_flagged_winners = deep_winners[deep_winners.predicted_class == "IMMEDIATE_FAILURE"]
            metrics_rows.append(dict(
                horizon_min=T, n=len(pT), auc=auc, sensitivity=sensitivity, specificity=specificity,
                precision=precision, false_positive_rate=1 - specificity if specificity is not None else None,
                deep_retrace_winner_false_protection_rate=(len(false_flagged_winners) / len(deep_winners)) if len(deep_winners) else None,
                discovery_auc_comparison=spec["horizon_models"][str(T)]["discovery_auc_insample"],
            ))
    else:
        metrics_rows.append(dict(status="OOS_ACCUMULATING", n=n_oos, minimum_required=MIN_OOS_TRADES,
                                  note="statistical metrics withheld per pre-registered protocol until n>=40"))
    pd.DataFrame(metrics_rows).to_csv(OUT / "task22_oos_metrics.csv", index=False)

    # Economic exposure (descriptive, reported regardless of n, but framed
    # as exposure only -- see Section 9's explicit "do not simulate P&L" instruction)
    for T in HORIZONS:
        pT = pred_df[pred_df.horizon_min == T]
        flagged_failures = pT[(pT.path_class == "IMMEDIATE_FAILURE") & (pT.predicted_class == "IMMEDIATE_FAILURE")]
        flagged_winners = pT[(pT.path_class == "DEEP_RETRACE_WINNER") & (pT.predicted_class == "IMMEDIATE_FAILURE")]
        econ_rows.append(dict(
            horizon_min=T,
            correctly_identified_immediate_failures=len(flagged_failures),
            failure_R_exposure_gross=flagged_failures["gross_R"].sum() if "gross_R" in flagged_failures.columns else None,
            falsely_flagged_deep_retrace_winners=len(flagged_winners),
            winner_R_exposure_gross=flagged_winners["gross_R"].sum() if "gross_R" in flagged_winners.columns else None,
            note="exposure metrics only -- NOT a P&L simulation of an early-exit rule, which has not been specified",
        ))
    pd.DataFrame(econ_rows).to_csv(OUT / "task22_economic_error.csv", index=False)

    # ------------------------------------------------------------------
    # Section 11/12: symbol / session monitoring (descriptive, all n)
    # ------------------------------------------------------------------
    sym_rows = []
    for sym, g in trades.groupby("symbol"):
        sym_rows.append(dict(symbol=sym, trades=len(g), path_class_counts=g.path_class.value_counts().to_dict()))
    pd.DataFrame(sym_rows).to_csv(OUT / "task22_symbol_analysis.csv", index=False)

    sess_rows = []
    for bucket, g in trades.groupby("session_bucket"):
        sess_rows.append(dict(session_bucket=bucket, trades=len(g), path_class_counts=g.path_class.value_counts().to_dict()))
    pd.DataFrame(sess_rows).to_csv(OUT / "task22_session_analysis.csv", index=False)

    # ------------------------------------------------------------------
    # final integrity dump
    # ------------------------------------------------------------------
    integrity.update(
        n_oos_trades=n_oos, status=status, path_class_counts=trades.path_class.value_counts().to_dict(),
        leakage_ok=leakage_ok, determinism_ok=determinism_ok,
        exit_reason_counts=trades.exit_reason.value_counts().to_dict(),
    )
    (OUT / "task22_integrity.json").write_text(json.dumps(integrity, indent=2, default=str))
    print("\nwrote task22_integrity.json")
    print(json.dumps(integrity, indent=2, default=str))
    print("\nAll sections complete.")
